# Generated by Django 5.1.2 on 2024-11-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_seatuserlink_date_of_departure_bustrip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="seat_configuration",
            field=models.CharField(
                choices=[("1x1", "1x1"), ("2x2", "2x2"), ("2x3", "2x3")], max_length=10
            ),
        ),
    ]
