# Generated by Django 5.1.2 on 2024-11-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_bus_seat_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="is_aisle",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bus",
            name="seat_configuration",
            field=models.CharField(
                choices=[
                    ("1x1", "1x1"),
                    ("2x2", "2x2"),
                    ("2x3", "2x3"),
                    ("Custom", "Custom"),
                ],
                max_length=10,
            ),
        ),
    ]
